export const constants = {
    taskUpdateToastrMsg : (update : string) => `Task has been successfully marked as ${update}`,
    taskDeleteToastrMsg : "Task deleted successfully",
    tasksdeleteToastrMsg : "Tasks Deleted succesully",
    taskAddToastrMsg : "Task added successfully",
    taskEditToastrMsg : "Task edited successfully",
    errorToastrMsg : "An unknown error occured",
    leadingSpaceTitle : "Dont enter leading spaces in Title",
    UserNamePasswordToastrMsg : "Enter valid username and password",
    invalidUserDetailsToastrMsg : "Invalid username or password",
    userAddedToastrMsg : "User added successfully",
    userExistsToastrMsg : "User already exists",
    titleDescToastrMsg : "Enter title and description!!",
    loginSuccessToastrMsg : "Login Successful",
    completeTaskHeading : "Today's Completed Tasks",
    taskUpdatePopUpMsg : (update : string) => `Confirm the task to be ${update}`,
    taskDeletePopUpMsg : "Confirm to delete the task",
    allTasksDeletePopUpMsg : "Confirm to delete all the tasks",
    activeTaskHeading : "Today's Active Tasks",
    activeCheckboxImage : "assets/Vector.png",
    completedCheckBoxImage : "assets/Vector1.png",
    activeBinImage : "assets/Orange Bin.png",
    completedBinImage : "assets/Red Bin.png",
    showPasswordImage : "assets/eye 1.svg",
    hidePasswordImage : "assets/clarity_eye-hide-line.png",
    signUp : "Sign Up",
    signIn : "Sign In",
    signInSubText : "Don’t have an account? Create ",
    signUpSubText : "Already have an account ? Sign in ",
    
}